name: flowlocker
services:
  surrealdb:
    entrypoint:
      - /surreal
      - start
      - --user
      - $SURREAL_DB_USER
      - --pass
      - $SURREAL_DB_PASSWORD
    image: surrealdb/surrealdb:latest
    ports:
      - "8000:8000"
