[package]
name = "flowlocker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# -- Database
surrealdb = { version = "1.0.0", features = ["kv-mem"] }
# -- async
tokio = { version = "1.34.0", features = ["full"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1"
# -- Web
axum = { version = "0.6.20", features = ["macros"] }
chrono = { version = "0.4.31", features = ["serde", "rustc-serialize"] }
parse_duration = "2.1.1"