[package]
name = "flowlocker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = { version = "1.0.0-beta.6", features = ["from"] }
surrealdb-beta = { version = "1.4.0", features = ["kv-mem"] }
once_cell = "1.19.0"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
uuid = { version = "1.8.0", features = ["v7"] }
serde = "1.0.200"
chrono = "0.4.38"
