[workspace.lints.rust]
unsafe_code = "forbid"
unused = "allow"

[workspace]
resolver = "2"
members = [
    "crates/libs/lib-core",
    "crates/libs/lib-utils",
    "crates/libs/lib-query-builder",
    "crates/apps/api",
]
